mode: parallel
max: 10
blueprint:
  name: Busy Room 0.1
  source_url: https://github.com/Evililim/HA-Blueprints/blob/main/busy_room.yaml
  homeassistant:
    min_version: 2024.6.0
  domain: automation
  author: Ev
  description: >-
    Uniformisation de la gestion de la presence dans chaque pièce via ce blueprint.

  input:
