mode: parallel
max: 10
blueprint:
  name: Busy Room 0.1
  source_url: https://github.com/Evililim/HA-Blueprints/blob/main/busy_room.yaml
  homeassistant:
    min_version: 2024.6.0
  domain: automation
  author: Ev
  description: >-
    Uniformisation de la gestion de la presence dans chaque pièce via ce blueprint.

  input:
    room_name:
        selector:
          area:
            multiple: false
        name: Pièce
        required: true
    doors:
        name: Portes (Ouverture)
        description: Capteurs ouverture des portes
        selector:
            entity:
              filter:
                device_class: door
    door_motion_entity:
      name: Portes (Mouvement)
      description: Capteurs de mouvement au niveau des portes
      selector:
        entity:
          filter:
            device_class: motion
    motion_entity:
      name: Mouvement
      description: Capteurs de mouvement dans la pièce
      selector:
        entity:
          filter:
            device_class: motion